import type { INodeType, INodeTypeDescription } from 'n8n-workflow';
import { NodeConnectionTypes } from 'n8n-workflow';

export class AsisChat implements INodeType {
  description: INodeTypeDescription = {
    displayName: 'asis.chat',
    name: 'asisChat',
    icon: 'file:asis.svg',
    group: ['output'],
    version: 1,
    subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
    description: "Run WhatsApp for a business over Meta's official Cloud API",
    defaults: { name: 'asis.chat' },
    usableAsTool: true,
    inputs: [NodeConnectionTypes.Main],
    outputs: [NodeConnectionTypes.Main],
    credentials: [{ name: 'asisChatApi', required: true }],
    requestDefaults: {
      baseURL: '={{$credentials.baseUrl}}',
      headers: { Accept: 'application/json' },
    },
    properties: [
      {
        displayName: 'Resource',
        name: 'resource',
        type: 'options',
        noDataExpression: true,
        default: 'message',
        options: [
          { name: 'Contact', value: 'contact' },
          { name: 'Conversation', value: 'conversation' },
          { name: 'Message', value: 'message' },
          { name: 'Template', value: 'template' },
        ],
      },

      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['message'] } },
        default: 'send',
        options: [
          {
            name: 'Send',
            value: 'send',
            action: 'Send a WhatsApp message',
            description:
              'Send a message to a phone number, creating the contact and conversation if needed. Free-form text only works inside the 24-hour customer service window; a template works at any time.',
            routing: { request: { method: 'POST', url: '/v1/messages' } },
          },
        ],
      },
      {
        displayName: 'To',
        name: 'to',
        type: 'string',
        default: '',
        required: true,
        placeholder: '+5491100000000',
        description: 'Recipient phone number in international format',
        displayOptions: { show: { resource: ['message'], operation: ['send'] } },
        routing: { send: { type: 'body', property: 'to' } },
      },
      {
        displayName: 'Send As',
        name: 'sendAs',
        type: 'options',
        default: 'body',
        description:
          'Free text needs the contact to have written in the last 24 hours. Outside that window WhatsApp only accepts an approved template.',
        displayOptions: { show: { resource: ['message'], operation: ['send'] } },
        options: [
          { name: 'Free Text (24h Window Must Be Open)', value: 'body' },
          { name: 'Approved Template (Works Anytime)', value: 'template' },
        ],
      },
      {
        displayName: 'Message',
        name: 'body',
        type: 'string',
        typeOptions: { rows: 3 },
        default: '',
        required: true,
        displayOptions: { show: { resource: ['message'], operation: ['send'], sendAs: ['body'] } },
        routing: { send: { type: 'body', property: 'body' } },
      },
      {
        displayName: 'Template ID',
        name: 'templateId',
        type: 'string',
        default: '',
        required: true,
        description: 'ID of an approved template. List them with the Template resource.',
        displayOptions: { show: { resource: ['message'], operation: ['send'], sendAs: ['template'] } },
        routing: { send: { type: 'body', property: 'templateId' } },
      },
      {
        displayName: 'Template Variables',
        name: 'variables',
        type: 'json',
        default: '{}',
        description: 'Values for the template placeholders, as a JSON object',
        displayOptions: { show: { resource: ['message'], operation: ['send'], sendAs: ['template'] } },
        routing: { send: { type: 'body', property: 'variables' } },
      },
      {
        displayName: 'Additional Fields',
        name: 'additionalFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: { show: { resource: ['message'], operation: ['send'] } },
        options: [
          {
            displayName: 'Contact Name',
            name: 'contactName',
            type: 'string',
            default: '',
            description: 'Name to give the contact if it does not exist yet',
            routing: { send: { type: 'body', property: 'contactName' } },
          },
          {
            displayName: 'Phone Number ID',
            name: 'phoneNumberId',
            type: 'string',
            default: '',
            description: 'Sending line. Required when the account has more than one WhatsApp number.',
            routing: { send: { type: 'body', property: 'phoneNumberId' } },
          },
        ],
      },

      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['conversation'] } },
        default: 'getAll',
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            action: 'Get many conversations',
            routing: { request: { method: 'GET', url: '/v1/conversations' } },
          },
          {
            name: 'Get',
            value: 'get',
            action: 'Get a conversation',
            routing: { request: { method: 'GET', url: '=/v1/conversations/{{$parameter["conversationId"]}}' } },
          },
          {
            name: 'Get Messages',
            value: 'getMessages',
            action: 'Get the messages of a conversation',
            routing: { request: { method: 'GET', url: '=/v1/conversations/{{$parameter["conversationId"]}}/messages' } },
          },
          {
            name: 'Reply',
            value: 'reply',
            action: 'Reply in a conversation',
            description: 'Send a free-form message inside an existing conversation. The 24-hour window must be open.',
            routing: { request: { method: 'POST', url: '=/v1/conversations/{{$parameter["conversationId"]}}/messages' } },
          },
        ],
      },
      {
        displayName: 'Conversation ID',
        name: 'conversationId',
        type: 'string',
        default: '',
        required: true,
        displayOptions: { show: { resource: ['conversation'], operation: ['get', 'getMessages', 'reply'] } },
      },
      {
        displayName: 'Message',
        name: 'body',
        type: 'string',
        typeOptions: { rows: 3 },
        default: '',
        required: true,
        displayOptions: { show: { resource: ['conversation'], operation: ['reply'] } },
        routing: { send: { type: 'body', property: 'body' } },
      },
      {
        displayName: 'Filters',
        name: 'filters',
        type: 'collection',
        placeholder: 'Add Filter',
        default: {},
        displayOptions: { show: { resource: ['conversation'], operation: ['getAll'] } },
        options: [
          {
            displayName: 'Status',
            name: 'status',
            type: 'options',
            default: 'active',
            options: [
              { name: 'Active', value: 'active' },
              { name: 'Unassigned', value: 'unassigned' },
            ],
            routing: { send: { type: 'query', property: 'status' } },
          },
          {
            displayName: 'Phone Number ID',
            name: 'phoneNumberId',
            type: 'string',
            default: '',
            routing: { send: { type: 'query', property: 'phoneNumberId' } },
          },
          {
            displayName: 'Limit',
            name: 'limit',
            type: 'number',
            typeOptions: { minValue: 1, maxValue: 100 },
            default: 20,
            description: 'Max number of results to return',
            routing: { send: { type: 'query', property: 'limit' } },
          },
        ],
      },

      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['contact'] } },
        default: 'getAll',
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            action: 'Get many contacts',
            routing: { request: { method: 'GET', url: '/v1/contacts' } },
          },
          {
            name: 'Create',
            value: 'create',
            action: 'Create a contact',
            description: 'Find or create a contact by phone number. An existing contact is returned untouched.',
            routing: { request: { method: 'POST', url: '/v1/contacts' } },
          },
        ],
      },
      {
        displayName: 'Search',
        name: 'search',
        type: 'string',
        default: '',
        description: 'Filter contacts by name or phone number',
        displayOptions: { show: { resource: ['contact'], operation: ['getAll'] } },
        routing: { send: { type: 'query', property: 'search' } },
      },
      {
        displayName: 'Phone',
        name: 'phone',
        type: 'string',
        default: '',
        required: true,
        displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
        routing: { send: { type: 'body', property: 'phone' } },
      },
      {
        displayName: 'Name',
        name: 'name',
        type: 'string',
        default: '',
        displayOptions: { show: { resource: ['contact'], operation: ['create'] } },
        routing: { send: { type: 'body', property: 'name' } },
      },

      {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: { show: { resource: ['template'] } },
        default: 'getAll',
        options: [
          {
            name: 'Get Many',
            value: 'getAll',
            action: 'Get many approved templates',
            routing: { request: { method: 'GET', url: '/v1/templates' } },
          },
        ],
      },
    ],
  };
}
