export enum ConversationEventType {
  CREATED = 'created',
  ASSIGNED = 'assigned',
  REASSIGNED = 'reassigned',
  UNASSIGNED = 'unassigned',
  RESOLVED = 'resolved',
  REOPENED = 'reopened',
  NOTE_ADDED = 'note_added',
  HANDOFF = 'handoff',
  LABEL_ADDED = 'label_added',
  LABEL_REMOVED = 'label_removed',
  CONTACT_UPDATED = 'contact_updated',
  GOAL_COMPLETED = 'goal_completed',
  FLOW_STARTED = 'flow_started',
  FLOW_COMPLETED = 'flow_completed',
  FLOW_FAILED = 'flow_failed',
  FLOW_STOPPED = 'flow_stopped',
  /** Piloto automático del chat: prendido / apagado (ver SetAutopilotUseCase) */
  AUTOPILOT_ON = 'autopilot_on',
  AUTOPILOT_OFF = 'autopilot_off',
}
