export enum ConversationEventType {
  CREATED = 'created',
  ASSIGNED = 'assigned',
  REASSIGNED = 'reassigned',
  UNASSIGNED = 'unassigned',
  RESOLVED = 'resolved',
  REOPENED = 'reopened',
  NOTE_ADDED = 'note_added',
  HANDOFF = 'handoff',
  LABEL_ADDED = 'label_added',
  LABEL_REMOVED = 'label_removed',
  CONTACT_UPDATED = 'contact_updated',
  GOAL_COMPLETED = 'goal_completed',
  ORDER_CREATED = 'order_created',
}
