upstream turnos_api { server turnos-api:3001; }

server {
    listen 80;
    server_name turnos.fluws.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    server_name turnos.fluws.com;
    ssl_certificate /etc/letsencrypt/live/turnos.fluws.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/turnos.fluws.com/privkey.pem;

    root /usr/share/nginx/html/turnos;

    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location ^~ /api/ {
        proxy_pass http://turnos_api;
        include /etc/nginx/proxy_params;
    }
    location / { try_files $uri $uri/ /index.html; }
}
